### ISSUE TITLE
Link user and room

### ISSUE THREAD

**Issue by Brawdunoir** [found-pleiade/dionysos-server#21]

**Comment by Brawdunoir** [comment]
Maybe use graphs (https://pkg.go.dev/github.com/arangodb/go-driver?utm_source=godoc#example-package-CreateGraph)
Users connected to a Room have a bidirectionnal vertice. And a request to join a room can be unidirectional
`UserA <-- connected --> Room <-- connected -- UserB`
UserA being for example the room owner.

**Comment by WhiteDiamondz** [comment]
Yeah  I want to explore graphs as well for this application.
I'm considering this approach:
Room X <-- User A means the User A is requesting to join the room X.
Room X --> User A means the room owner is inviting (via the room) the User A to join the room.
Room X <--> User A means the User A is connected to the room X

**Comment by Brawdunoir** [comment]
Done
