### ISSUE TITLE
Fix Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by vazanoir** [found-pleiade/dionysos-server#32]
![Request result](https://user-images.githubusercontent.com/50767291/177885919-8f491bdd-e33a-427d-a71e-b2e073a82bdb.png)

**Comment by Brawdunoir** [comment]
Still have the problem, will allow everyone via CORS.
We will need to add api keys to allow only the client to talk with our api in the future (to be added as an env var during releasing process in the pipeline ?)
source: https://stackoverflow.com/questions/43154170/is-it-safe-to-enable-cors-to-for-a-public-and-readonly-webservice/43154277#43154277

**Comment by Brawdunoir** [comment]
Still having issues
